### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by TedTdist12** [code4recovery/sheets#14]
I have followed the instructions on the google sheets importer page, click on import.

Then a server error 500 is returned.

Can someone help us?

Regards,
Ted

**Comment by joshreisner** [comment]
hi ted, what's the sheet URL?

**Comment by TedTdist12** [comment]
Hello Josh,

https://docs.google.com/spreadsheets/d/1cERocR4UEey_Hoq_pJkDI6XSLm2b-C0v6XyiSEiGWKQ/edit?usp=sharing

Regards,
Ted

**Comment by joshreisner** [comment]
Ah ok thanks. Try it again, it should work now. 

It's a relatively new service, and you were the first to have blank rows in the data, which now should be no problem.

Also now it reports when it skips a row because it sees an empty ID column

**Comment by TedTdist12** [comment]
Hello,

That part is working now, thanks.

In the notes there is a statement " Feeds that are not refreshed within 30
days are removed automatically"

Does this mean we need to refresh every so often?  If so how often?
I was thinking if we maintain the Google sheet schedule everything would be
updated automatically. This is new to me, I am trying to fill in, and help
out.

Regards,
Ted

**Comment by joshreisner** [comment]
great, glad to hear it.

think of the sheet like a draft now. every time there's an update you'll need to visit the refresh URL to publish the changes so that users can see them

if a sheet goes more than 30 days without a refresh it's removed so that we're not showing stale data to users

**Comment by TedTdist12** [comment]
Side note

The PDF generator is working for the sheet, but not for the JSON.

Regards,
Ted

**Comment by joshreisner** [comment]
ah thanks. that should be fixed now
