### ISSUE TITLE
Inactive Tag

### ISSUE THREAD

**Issue by leggomyinfo** [code4recovery/sheets#15]
Meetings have started showing up at https://aasfmarin.org/find-a-meeting with an Inactive tag that SF/Marin has deleted from Airtable (see Friday At Five in screenshot). We're hoping to stop that from happening.

They disappeared after I refreshed the JSON feed.

What's happening exactly?

<img width="1280" alt="Screen Shot 2022-12-23 at 6 57 58 PM" src="https://user-images.githubusercontent.com/58055115/209414349-1df49929-be00-4ebf-812d-83c89953e8dc.png">

**Comment by leggomyinfo** [comment]
Do you have any logs to see which meetings had the inactive tag prior to the last JSON refresh?

The two meetings I saw with an Inactive both had already been deleted from Airtable, but perhaps that was a coincidence and they were still in Airtable before the last refresh with just bad data.

Why wouldn't meetings with bad data show up among the other import errors rather than appear with the Inactive tag?

**Comment by joshreisner** [comment]
no logs, sorry

it sounds like they showed up to the sheets importer as approximate meetings with no conference url - i dont think that was programmed as an invalid state, like an unrecognized provider or an unexpected type would be

if it happens again i can take a look

**Comment by leggomyinfo** [comment]
Most of the meetings tagged as inactive are no longer showing up because Marcus has been deleting them (as expected). I'll apply filters (re-apply? i think we had them and they may have been turned off) so these don't get passed to TSML to begin with.

**Comment by joshreisner** [comment]
ok sounds good thanks 👍 

sounds like i can close

**Comment by leggomyinfo** [comment]
The remaining inactive meetings are now filtered out and I refreshed the JSON feed.

+1 for treating these as import errors rather than using an Inactive tag, but no biggie on our end either way
