### ISSUE TITLE
Import Multiple Feeds

### ISSUE THREAD

**Issue by mathteacher** [code4recovery/sheets#16]
Would it be possible for the TSML UI to accept multiple feeds?

In Area 72 (Western Washington) there are several scenarios where multiple websites want to display the same meetings, and we would like to have them be hosted only in a single database and then imported to both of the websites. Here's one example:

The Puget Sound Central Service Office (PSCSO) utilizes TSML UI and a Google Sheet to manage and present the meeting info for its seven member districts. One of those districts, District 54, is on the edge of King County and some of its meetings actually are in King County, and thus they are also listed on the Greater Seattle Intergroup (GSI) website that utilizes the 12-Step-Meeting-List WP plugin. The problem arises when one of those District 54 meetings changes its address/day/time but the changes aren't reported to both the PSCSO and GSI, so then both the correct and incorrect version of the meeting gets displayed on the Meeting Guide app and the Area 72 website (which imports from both groups).

One solution I've thought of would be for the PSCSO to separate its District 54 meetings into its own Google Sheet so that the GSI could then import just those meetings to its meeting database (but not the meetings from the other six districts of the PSCSO). But for this to work the PSCSO TSML UI would need to be able to accept/import multiple feeds since there will now be two Google Sheets of meeting data (D54 and other 6 districts) that need to be displayed together on their meeting website.

**Comment by joshreisner** [comment]
ok, i've created a combined feed at https://sheets.code4recovery.org/storage/puget-sound.json which should work with TSML UI

you can refresh it by visiting https://sheets.code4recovery.org/puget-sound

let me know what you think

**Comment by joshreisner** [comment]
good. 

yeah should be fine to make to make adjustments as needed. going to close this issue for now
