### ISSUE TITLE
disconnecting google sheet from meeting-finder

### ISSUE THREAD

**Issue by jlabenberg** [code4recovery/sheets#19]
I inherited a very old Dreamweaver website and our meetings are connected to meeting-finder via a google-sheet/doc.

I finally tracked down someone from the past who gave me access to the google-doc and I see the owner is Meeting-Finder with original creator Josh. R. who I've learned is part of Meeting Finder and not someone locally from the past.

I would like to disconnect my local google-sheet from meeting finder so that I can connect via the 12-Step-Meeting-Finder list in our new WordPress version of our website.

How do I do it?

**Comment by joshreisner** [comment]
hi @jlabenberg just let appsupport@aa.org know and they will switch it for you

**Comment by jlabenberg** [comment]
hi @joshreisner - than you so much for the quick response - I also need the google doc disconnected from my associated AREA website as well since they have access to is as well and they want it disconnected from them before they connect to my TSML version - will appsupport@aa.org help me with that as well?

**Comment by joshreisner** [comment]
when you say "disconnected from" you mean the area is importing your google sheet data and displaying it on their site? if so, then the area webservant can do that on the area website by removing it at meetings > import & export
