### ISSUE TITLE
Address fields not copied over to JSON?

### ISSUE THREAD

**Issue by jeznag** [code4recovery/sheets#21]
I have this spreadsheet: https://docs.google.com/spreadsheets/d/1YRpUph8Xfw-hX-2IegFx_S4YQUprFTqLPYxfL42Pb98/edit#gid=0

The JSON doesn't capture city, state or country: https://sheets.code4recovery.org/storage/1YRpUph8Xfw-hX-2IegFx_S4YQUprFTqLPYxfL42Pb98.json

Did I use the wrong column names?

**Comment by joshreisner** [comment]
no, you did it correctly, you just needed to refresh your feed. i did it for you just now to confirm. your refresh URL is https://sheets.code4recovery.org/1YRpUph8Xfw-hX-2IegFx_S4YQUprFTqLPYxfL42Pb98

typically you shouldn't need both formated address and the other address fields. one or the other should work
