### ISSUE TITLE
How do I refresh the JSON data?

### ISSUE THREAD

**Issue by jeznag** [code4recovery/sheets#22]
It seems like the spreadsheet gets fetched once per day or something? Can I use a query parameter to bust the cache and re-fetch?

**Comment by joshreisner** [comment]
feeds are refreshed every time you manually resubmit your feed or simply visit your feed refresh page, which in your case is https://sheets.code4recovery.org/1YRpUph8Xfw-hX-2IegFx_S4YQUprFTqLPYxfL42Pb98

there is no caching limit - you can visit that page as much as you like. you will need to visit it once a month at minimum

one thing some groups do is make use of the redirectTo query param to make a link column in their sheet using appscript - this can link you from the row > feed refresh > meeting detail page
