### ISSUE TITLE
Could we add support for other fields found in TSML

### ISSUE THREAD

**Issue by anchovie91471** [code4recovery/sheets#27]
This service already supports non-spec fields like District, Districts, Email, etc.

Would it be possible to support all the fields TSML provides for meetings (including contact fields, website 2, sub-regions, mailing address, etc.)? What would be the drawbacks to this.

I think being able to add these fields to a google sheet and get these included in the json output would make sense when importing to TSML.

Thoughts?

**Comment by joshreisner** [comment]
we can add the contact fields for sure, and i can go through the other fields to see which are supported by TSML UI but not sheets and add those as well

sheets can be imported directly to TSML, so the focus of this application is just for making a sheet available to TSML UI and meeting guide

`mailing_address` and `website_2` aren't supported by TSML UI or Meeting Guide - i'd be more in favor of removing those from the plugin and the spec, i think they're confusing to have in there tbh
