### ISSUE TITLE
To deploy an Add-on to the Google Workspace Marketplace, you'll need to switch this Apps Script project to use a user-managed Google Cloud Platform (GCP) project.

### ISSUE THREAD

**Issue by wvaughn409** [code4recovery/sheets#31]
I was curious how to use this so I made some test data in a google sheet:
![image](https://github.com/code4recovery/sheets/assets/9452611/11d2a710-97e3-47b8-a32b-f1b0f9248720)
...and then clicked Extensions>Apps Script and pasted the code. But when I tried to do a deployment, I get the error saying:
Add-on
This Apps Script project is using an Apps Script-managed Google Cloud Platform (GCP) project.
To deploy an Add-on to the Google Workspace Marketplace, you'll need to switch this Apps Script project to use a user-managed Google Cloud Platform (GCP) project.[ Learn more ](https://developers.google.com/apps-script/guides/cloud-platform-projects#switch_to_a_different_google_cloud_platform_project)about GCP project types.

Do I need to be added as a G-Suite user in the domain before I can sandbox this, or am I doing something wrong?
I selected "Add-On" for type of deployment, and I'm just using a normal gmail account.

-Chris V

**Comment by joshreisner** [comment]
hm, this project is for websites to list recovery meetings - is that something you're trying to do?

**Comment by wvaughn409** [comment]
Hey there! thanks for responding. I sent you a message on LinkedIn, if that's okay?
