### ISSUE TITLE
TSML Changes Location data from Sheets

### ISSUE THREAD

**Issue by marian1943** [code4recovery/sheets#34]
I have several meetings at same location (ie Plaza...) but in separate rooms. If I make a change to one meeting on the Sheet, TSML makes that change to ALL locations when I import and refresh. This has been happening on various Sheets for a year or more.

![IMG_20241125_133421657](https://github.com/user-attachments/assets/7e79718f-a86b-4f49-b3c8-492ef0134da7)
![IMG_20241125_134449491](https://github.com/user-attachments/assets/0470e830-8642-4416-a8a9-059e7194db78)

**Comment by marian1943** [comment]
I'm disappointed but OK. The reason I like the extra info added in the Locations is because when the map comes up in TSML, the important info is prominently displayed on the pop up.

**Comment by joshreisner** [comment]
this limitation comes from the tsml plugin and the meeting guide app--they're not capable of displaying different location names for different meetings at the same address 🤷
